#!/bin/sh

case "$(echo " Suspend\n Shutdown\n Restart\n Logout" | dmenu \
    -nb black \
    -nf white \
    -sf teal \
    -sb "#1a1a1a" \
    -t -c -i -p \
    "Power:" -l 4 | cut -c 5-)" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Logout) i3-msg exit;;
        Suspend) exec systemctl suspend;;
esac
